title: willuhd
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
locale: "en-US"
url: https://willuhd.github.io
baseurl: ""

# Add Google Fonts for non-Apple devices
head_scripts:
  - https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      share: false
      comments: false
      read_time: false
      sidebar:
        nav: "auto"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap