title: willuhd
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
locale: "en-US"
url: https://willuhd.github.io
baseurl: ""

feed: false

collections:
  sections:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: false
      share: false  
      comments: false
      read_time: false

  - scope:
      path: "_sections/gpa-calc"
    values:
      sidebar:
        nav: "gpa-calc-sidebar" 

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
