title: willuhd
locale: "en-US"
url: https://willuhd.github.io
permalink: /:title/
baseurl: ""

head_scripts:
  - https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      share: false
      comments: false
      read_time: false
      sidebar:
        nav: "auto"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
